### ISSUE TITLE
broken on case-relaxed disks

### ISSUE THREAD

**Issue by coke** [finanalyst/collection-plugins#1] opened 2023-08-02 23:12 UTC
see https://github.com/finanalyst/collection/issues/3

the issue is that https://github.com/finanalyst/collection-plugins/tree/main/plugins/html/typegraph_v0_auth_collection has both Int.svg *and* int.svg.

**Comment by finanalyst** [comment] 2023-08-07 10:32
@coke Each `.svg` corresponds to the name of `Type` rakudoc document. If there is `Raku/docs/doc/Type/Int.rakudoc` and `Raku/docs/doc/Type/int.rakudoc`, then both `Int.svg` and `int.svg` are expected.

Is there a standard way of dealing with this naming problem for case-relaxed disks?

**Comment by coke** [comment] 2023-08-07 11:12
The fix is to rename the files to avoid the issue (in this case, maybe have int.svg be native/int.svg or native_int.svg), or to not use a case-insensitive disk.

I find that using case-overlapping file names is like using NUL as a file name. (and should be avoided, even if it works on my setup)

**Comment by coke** [comment] 2023-08-07 11:52
Also: Raku/docs does not have both of those files.

**Comment by finanalyst** [comment] 2023-08-08 10:38
@coke, I believe you are mistaken. Searching on a local clone of Raku/docs I have:
```
 rak 'int.rakudoc' --find
local_raku_docs/doc/Native/int.rakudoc
local_raku_docs/doc/Type/atomicint.rakudoc

$ rak 'Int.rakudoc' --find
local_raku_docs/doc/Type/Int.rakudoc
local_raku_docs/doc/Type/UInt.rakudoc
```

**Comment by coke** [comment] 2023-08-08 11:31
the problem isn't in raku/docs. It's in collection-plugins - the URL I posted at the top of the ticket.

**Comment by finanalyst** [comment] 2023-08-08 17:53
@coke I think we are misunderstanding each other because we see the problem as being in different places. Allow me to explain. I do want to fix this long-standing problem.

The URL you posted does indeed point to the typegraph plugin. And yes, indeed, there is an svg called `int.svg` and one called `Int.svg`. This is not an innovation in collection plugin, but something that Documentable did. 

The source of the svg's for both the Collection-plugin Typegraph plugin, and Documentable is the [Typegraph module ](https://github.com/JJ/Raku-Doc-TypeGraph)

The Typegraph module generates svg's that are named for each entity in typegraph.txt, which I think was compiled from `Raku/docs/doc/Type/`, and for some others, such as 'int'.

The behaviour in Documentable (and copied for Collection typegraph) was to match the name of the `rakudoc` file with the svg. So when I said the problem is in `Raku/docs`, it is partly true. There are two rakudoc files: `Raku/docs/doc/Type/Int.rakudoc` and `Raku/docs/doc/Native/int.rakudoc`. Documentable and Collection-plugin-typegraph match the `int` & `Int` in the document name to the svgs.

The resolution of the problem may be found elsewhere. As can be seen in the generation document of Typegraph [there are both int and Int](https://github.com/JJ/Raku-Doc-TypeGraph/blob/1f0217d96027e2f8566dcc25c85b1af9ce1b409e/type-graph.txt#L128C1-L135C43)

So, what we need is for svgs to be generated that are not case-sensitive, and for the name of the document to match the svg.

There are three ways I think this can be solved:
- more of the entity name needs to be added to the svg - but this does not work for `Int` and `int` which are both classes. So there is insufficient information on `typegraph.txt` to differentiate between them.
- hash code the names in some way so that they are not the same eg. change each char to a hex representation of the names.

The second is probably the easiest way to do this. But it will mean changing all the svg names on doc-website.

**Comment by coke** [comment] 2023-08-08 19:57
Given that we don't direct link to the svgs (only include them), I think it's fine to obfuscate them slightly. We could also have a "native" folder and put only the lowercase ones in it.

**Comment by finanalyst** [comment] 2023-08-09 08:42
@coke There is a link at the bottom of each Typegraph too, but its a part of the Typegraph section.
So the slight obfuscation to be applied on svgs and where svgs are used
- test for special file names
- if special add prefix 'native-' to the svg

As for the test, I thought maybe only test for 1st char, as that is the only place where we know it matters. But generically there could be a upper-case/lower-case duplicate anywhere in the file name.

So my suggestion now is to hard code a list of filenames to test, with `int` being the first. If we find more upper-case/lower-case duplicates, we can add them to the list.

If you're happy with this, I'll fix asap

**Comment by coke** [comment] 2023-08-09 14:39
New native classes are unlikely to be added often, static is fine.

**Comment by finanalyst** [comment] 2023-08-09 20:02
Of the 423 svgs, only Int and int are case-insensitive duplicates

**Comment by coke** [comment] 2023-08-09 20:31
I don’t see the fix.

**Comment by finanalyst** [comment] 2023-08-09 21:44
@coke not fixed yet. Still working on it. I was waiting for you to say the suggested fix was OK

**Comment by finanalyst** [comment] 2023-08-09 21:47
There are 423 svgs, but only 336 rakudoc files under `Raku/docs/doc/Type/`, so which other files were getting Typegraphs before?????

**Comment by coke** [comment] 2023-08-09 21:58
> @coke not fixed yet. Still working on it. I was waiting for you to say the suggested fix was OK

You closed it as completed, though.

**Comment by finanalyst** [comment] 2023-08-09 22:56
@coke It's late and my head's woozy. I had not realised I closed the issue. A mouse-slip.

**Comment by finanalyst** [comment] 2023-08-09 23:13
I have just run a script on `type-graph.text` matching names in the second column (eg int) with filenames (with `::` replaced by `/`). There are 94 elements listed in `type-graph.txt` for which there is no rakudoc file under either `Type/` or `Native/`

`type-graph.txt` is used to derive the Typegraph svgs. I am not aware of how `type-graph.txt` was generated.

The missing entities are listed below. Are these missing documentation files?

I've included the file in the last commit to `collection-plugins/plugins/html/typegraph/`

There is a glitch in the parsing of `type-graph.txt` because I did not properly parse roles with parameters, eg `role  Callable[::T = Mu]` There are about 10 such roles. In 'not-in-docs' they appear as eg `role  Callable[/T`

**Comment by finanalyst** [comment] 2023-08-10 09:35
@coke  I implemented a fix, but there is a residual problem. Typegraph creates links on all nodes of the image. In the `Int` typegraph we have `int`, but the link is to `type/int` not `native/int`

By special casing 'int' all the references in the Typegraphs to `int` are messed up. This, however, is not something I **easily** fix in the typegraph plugin.

The solution might be to add a column in the `type-graph.txt` file that defines where the node should point.

**Comment by finanalyst** [comment] 2023-08-10 09:37
I'll run this for 'new-raku', then create a PR for doc-website if it builds correctly.

**Comment by finanalyst** [comment] 2023-08-10 10:05
@coke this is now working on new-raku [For example int](https://new-raku.finanalyst.org/native/int)

closing as complete

**Closed as completed by finanalyst** 2023-08-10 10:05 UTC
